/**
 * A model identifier — either a string (gateway format like "anthropic/claude-sonnet-4")
 * or an AI SDK LanguageModel instance.
 */
export type LanguageModel = string | import("ai").LanguageModel;

// --- Stream types ---

export interface SendOptions {
  /** Override system prompt for this request */
  system?: string;
  /** Override the model for this single request (does not change the default). */
  model?: string;
}

/**
 * Common stream options shared across all framework wrappers.
 * Framework-specific StreamOptions<M> extend this and add `model?: M`.
 */
export interface BaseStreamOptions {
  system?: string;
  endpoint: string;
  fetch?: typeof globalThis.fetch;
  onFinish?: (text: string) => void;
  onError?: (error: Error) => void;
  /**
   * Session ID for server-side conversation history.
   * When set, the server maintains multi-turn context via ConversationStore.
   */
  sessionId?: string;
  /**
   * Automatically select a model for each request based on the prompt.
   * Called before every send unless an explicit `model` is passed in send options.
   * Priority: explicit send override > routeModel > constructor model default.
   */
  routeModel?: (prompt: string) => string | Promise<string>;
  /**
   * Accumulate token usage and cost across turns.
   * Pass a UsageTracker instance — it will be updated after every completed stream.
   */
  tracker?: UsageRecorder;
  /**
   * Compute a diff against the previous response after each regenerate/send.
   * `stream.diff` is `null` on the first send, populated on every subsequent one.
   *
   * Pass `defaultDiff` from `@aibind/core` for the built-in word-level LCS diff,
   * or provide your own function to use any diff library.
   * Omit to disable diffing (default).
   */
  diff?: DiffFn;
  /**
   * Artifact extraction configuration.
   * When set, the stream will scan each line through the provided detector
   * and populate `stream.artifacts` / `stream.activeArtifact` as markers appear.
   */
  artifact?: { detector: import("./artifacts").ArtifactDetector };
}

/**
 * Token usage returned after each completed stream turn.
 * `inputTokens` reflects the full context size (history + new message) —
 * use it to decide when to compact.
 */
export interface StreamUsage {
  /** Total input tokens for this turn (includes full conversation history). */
  inputTokens: number;
  /** Output tokens generated by the model for this turn. */
  outputTokens: number;
}

export type StreamStatus =
  | "idle"
  | "streaming"
  | "stopped"
  | "done"
  | "reconnecting"
  | "disconnected"
  | "error";

// --- Agent types ---

export type AgentStatus = "idle" | "running" | "awaiting-approval" | "error";

export type ToolCallStatus = "running" | "completed" | "error";

export interface AgentMessage {
  id: string;
  role: "user" | "assistant" | "tool";
  content: string;
  type: "text" | "tool-call" | "tool-result" | "approval-request";
  /** Tool call identifier (links tool-call and tool-result messages). */
  toolCallId?: string;
  toolName?: string;
  args?: unknown;
  result?: unknown;
  toolError?: string;
  toolStatus?: ToolCallStatus;
  /** Approval ID for approval-request messages. */
  approvalId?: string;
}

export interface AgentOptions {
  /** API endpoint for the agent. */
  endpoint: string;
  /** Custom fetch implementation. Defaults to globalThis.fetch. */
  fetch?: typeof globalThis.fetch;
  /**
   * Named toolset to activate. Must match a key in the server agent's `toolsets`.
   * Omitting this uses the server's configured default (if any), or no tools.
   */
  toolset?: string;
  onMessage?: (message: AgentMessage) => void;
  onError?: (error: Error) => void;
}

// --- Completion types ---

export interface CompletionCallbacks {
  onSuggestion(suggestion: string): void;
  onLoading(loading: boolean): void;
  onError(error: Error | null): void;
}

export interface BaseCompletionOptions {
  /** API endpoint. Defaults to '/__aibind__/complete'. */
  endpoint?: string;
  /** Model key for completions. */
  model?: string;
  /** System prompt override for the completion model. */
  system?: string;
  /** Debounce delay in ms. Default: 300. */
  debounce?: number;
  /** Minimum input length before triggering a completion request. Default: 3. */
  minLength?: number;
  /** Custom fetch implementation. Defaults to globalThis.fetch. */
  fetch?: typeof globalThis.fetch;
  /** Called when a suggestion is received. */
  onFinish?: (suggestion: string) => void;
  /** Called when an error occurs. */
  onError?: (error: Error) => void;
}

// --- Diff types ---

/** A single chunk produced by a diff computation. */
export interface DiffChunk {
  type: "keep" | "add" | "remove";
  text: string;
}

/**
 * Diff function signature. Takes two strings and returns a list of chunks.
 * aibind ships a built-in word-level LCS diff; pass your own to use any library.
 */
export type DiffFn = (prev: string, next: string) => DiffChunk[];

// --- Usage tracking ---

/**
 * Minimal interface satisfied by UsageTracker.
 * Pass any object with a `record` method as the `tracker` option in StreamOptions / useStream.
 */
export interface UsageRecorder {
  record(usage: StreamUsage, model?: string): void;
}

// --- Utility types ---

/** Deep partial — makes all nested properties optional */
export type DeepPartial<T> = T extends object
  ? { [P in keyof T]?: DeepPartial<T[P]> }
  : T;

// --- Chat types ---

export interface Attachment {
  /** MIME type of the attachment, e.g. "image/png", "application/pdf". */
  mimeType: string;
  /** Base64-encoded content (no `data:` prefix). Mutually exclusive with `url`. */
  data?: string;
  /** Remote URL. Mutually exclusive with `data`. */
  url?: string;
}

export interface ChatSendOptions {
  /** File or image attachments to include with the message. */
  attachments?: Attachment[];
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  /** True from `send()` until the first chunk arrives. Use to show pending UI. */
  optimistic?: boolean;
  /** Attachments included with this message (user messages only). */
  attachments?: Attachment[];
}

/**
 * Handle returned by `Chat.optimistic()` / `useChat().optimistic()`.
 * The message is already visible in the UI — call `send()` to stream the
 * response, or `cancel()` to discard both messages.
 */
export interface StagedMessage {
  /** Start the actual streaming request for the staged message. */
  send(): void;
  /** Remove the staged messages without sending. */
  cancel(): void;
}

export interface ChatCallbacks {
  onMessages(messages: ChatMessage[]): void;
  onLoading(loading: boolean): void;
  onError(error: Error | null): void;
  onStatus(status: StreamStatus): void;
}

export interface BaseChatOptions {
  /** API endpoint for the chat handler (e.g. '/__aibind__/chat'). */
  endpoint: string;
  /** Optional system prompt sent with every request. */
  system?: string;
  /** Override model key sent in the request body. */
  model?: string;
  /** Custom fetch implementation. */
  fetch?: typeof globalThis.fetch;
  /** Called when a turn completes with the full messages array. */
  onFinish?: (messages: ChatMessage[]) => void;
  /** Called when a network or server error occurs. */
  onError?: (error: Error) => void;
  /**
   * Named toolset to activate for this chat instance.
   * Must match a key registered in `createStreamHandler({ toolsets: { ... } })`.
   * Omitting this option disables tool calling entirely for this instance.
   */
  toolset?: string;
  /**
   * Maximum tool-call → result → LLM rounds per turn.
   * Only applied when a toolset is active. Defaults to 5.
   */
  maxSteps?: number;
  /**
   * Called each time the model invokes a tool before producing the final response.
   * Useful for showing "Searching…" or progress feedback in the UI.
   */
  onToolCall?: (name: string, args: unknown) => void;
}

// --- defineModels ---

/**
 * Define named AI models for type-safe model selection across client and server.
 */
export function defineModels<const T extends Record<string, LanguageModel>>(
  models: T,
): T {
  return models;
}
