/**
 * A model identifier — either a string (gateway format like "anthropic/claude-sonnet-4")
 * or an AI SDK LanguageModel instance.
 */
export type LanguageModel = string | import("ai").LanguageModel;

// --- Stream types ---

export interface SendOptions {
  /** Override system prompt for this request */
  system?: string;
  /** Override the model for this single request (does not change the default). */
  model?: string;
}

/**
 * Common stream options shared across all framework wrappers.
 * Framework-specific StreamOptions<M> extend this and add `model?: M`.
 */
export interface BaseStreamOptions {
  system?: string;
  endpoint: string;
  fetch?: typeof globalThis.fetch;
  onFinish?: (text: string) => void;
  onError?: (error: Error) => void;
  /**
   * Session ID for server-side conversation history.
   * When set, the server maintains multi-turn context via ConversationStore.
   */
  sessionId?: string;
  /**
   * Automatically select a model for each request based on the prompt.
   * Called before every send unless an explicit `model` is passed in send options.
   * Priority: explicit send override > routeModel > constructor model default.
   */
  routeModel?: (prompt: string) => string | Promise<string>;
}

/**
 * Token usage returned after each completed stream turn.
 * `inputTokens` reflects the full context size (history + new message) —
 * use it to decide when to compact.
 */
export interface StreamUsage {
  /** Total input tokens for this turn (includes full conversation history). */
  inputTokens: number;
  /** Output tokens generated by the model for this turn. */
  outputTokens: number;
}

export type StreamStatus =
  | "idle"
  | "streaming"
  | "stopped"
  | "done"
  | "reconnecting"
  | "disconnected"
  | "error";

// --- Agent types ---

export type AgentStatus = "idle" | "running" | "awaiting-approval" | "error";

export type ToolCallStatus = "running" | "completed" | "error";

export interface AgentMessage {
  id: string;
  role: "user" | "assistant" | "tool";
  content: string;
  type: "text" | "tool-call" | "tool-result" | "approval-request";
  /** Tool call identifier (links tool-call and tool-result messages). */
  toolCallId?: string;
  toolName?: string;
  args?: unknown;
  result?: unknown;
  toolError?: string;
  toolStatus?: ToolCallStatus;
  /** Approval ID for approval-request messages. */
  approvalId?: string;
}

export interface AgentOptions {
  /** API endpoint for the agent. */
  endpoint: string;
  /** Custom fetch implementation. Defaults to globalThis.fetch. */
  fetch?: typeof globalThis.fetch;
  onMessage?: (message: AgentMessage) => void;
  onError?: (error: Error) => void;
}

// --- Completion types ---

export interface CompletionCallbacks {
  onSuggestion(suggestion: string): void;
  onLoading(loading: boolean): void;
  onError(error: Error | null): void;
}

export interface BaseCompletionOptions {
  /** API endpoint. Defaults to '/__aibind__/complete'. */
  endpoint?: string;
  /** Model key for completions. */
  model?: string;
  /** System prompt override for the completion model. */
  system?: string;
  /** Debounce delay in ms. Default: 300. */
  debounce?: number;
  /** Minimum input length before triggering a completion request. Default: 3. */
  minLength?: number;
  /** Custom fetch implementation. Defaults to globalThis.fetch. */
  fetch?: typeof globalThis.fetch;
  /** Called when a suggestion is received. */
  onFinish?: (suggestion: string) => void;
  /** Called when an error occurs. */
  onError?: (error: Error) => void;
}

// --- Utility types ---

/** Deep partial — makes all nested properties optional */
export type DeepPartial<T> = T extends object
  ? { [P in keyof T]?: DeepPartial<T[P]> }
  : T;

// --- defineModels ---

/**
 * Define named AI models for type-safe model selection across client and server.
 */
export function defineModels<const T extends Record<string, LanguageModel>>(
  models: T,
): T {
  return models;
}
